### ISSUE TITLE
Acquire Zebrafish Data

### ISSUE THREAD

**Issue by devoworm** [balicea/DevoWorm#117]

**Comment by DrKenHo** [comment]
Keller (2010)
https://www.ncbi.nlm.nih.gov/pubmed/20601950

Open quantitative data for that can be found here at SSBD
http://ssbd.qbic.riken.jp/resources/?value=18845710+[PMID]&form-submit=Search

**Comment by Orthogonal-Research-Lab** [comment]
Thank you Ken! Bradly will look into these.
