### ISSUE TITLE
Incorporate Gephi (network drawing tool) into DevoWorm toolbox

### ISSUE THREAD

**Issue by balicea** [balicea/DevoWorm#46]

**Comment by balicea** [comment]
Mark Watts is interested in contributing to plug-in development. Request access to data, other info if interested.

**Comment by mwatts15** [comment]
Currently, I'm blocked on this due to a segfault I experience when starting Gephi. I filed the initial bug report on [OpenJDK's bug tracker](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2950). I pulled the most recent version of jogl from source to test with before I created a bug report, but got "class not found" exceptions for:
- com.jogamp.common.nio.Buffers
- com.jogamp.common.os.Platform

and was unable to reproduce the original segfault. However, I am able to *start* Gephi with this change, which is better than what I had before. I'm looking to see where those classes are defined.

**Comment by mwatts15** [comment]
I was missing the gluegen libraries. Adding them back, I'm able to reproduce the crash. I'm going ahead with the bug report.

**Comment by mwatts15** [comment]
One more quick update: after updating some of my mesa drivers, and opengl libraries, gephi starts up without any errors reported. I'll still try to track down which library was causing the failure, but am at least able to start Gephi on my dev machine now.

**Comment by mwatts15** [comment]
I've imported data from the Differentiation Tree data set into Gephi, but from there I've had no luck getting a more useful visualization. I made [a script](https://gist.github.com/mwatts15/88845ce75249235238dd09beffc9aa87) that turns the daughter-of relationships into edges.

**Comment by mwatts15** [comment]
Also, looking at a possibly inconsistent row:
```
404	ABplapapa	ABplapapaa	ABplapapaa	B	0	0	ABplapapaa
```

**Comment by balicea** [comment]
Mark,

      Thanks. We can discuss this in more detail soon.


On 5/21/2016 10:43 AM, Mark Watts wrote:
>
> I've imported data from the Differentiation Tree data set into Gephi, 
> but from there I've had no luck getting a more useful visualization. I 
> made a script 
> <https://gist.github.com/mwatts15/88845ce75249235238dd09beffc9aa87> 
> that turns the daughter-of relationships into edges.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/balicea/DevoWorm/issues/46#issuecomment-220784702>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by balicea** [comment]
Mark,

      There are a few rows like this in the dataset -- some mother cells 
do not result in two daughter cells. In this case, the parent only gives 
rise to a single daughter for which there is no data. In such cases, 
please exclude from your copy of the data (do not delete from the master 
copy). Thanks.


On 5/21/2016 11:13 AM, Mark Watts wrote:
>
> Also, looking at a possibly inconsistent row:
>
> |404 ABplapapa ABplapapaa ABplapapaa B 0 0 ABplapapaa |
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/balicea/DevoWorm/issues/46#issuecomment-220786284>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by mwatts15** [comment]
@balicea in other places, I see that there is only one daughter entry, either A or B. For some of these, the 'Larger Cell' column shows 'X' for missing when there's only one cell, and for others it shows 'A' when there's only an A daughter cell. The row in my comment above is the only one where the same daughter cell is in both A and B columns.
Looking at Sulston et al's lineage tree it looks like:
```
406	ABplapapaa			X	0	0
```
should be 
```
406	ABplapapap			X	0	0
```
except that, post-ebryonic blast cells are excluded from this data set, so I think I'd just delete that line except that there's separate positional data for 405 and 406. Is there any guidance on how to resolve this? If not I'll try to highlight this data in some way in a visualization.

**Comment by balicea** [comment]
Mark,

      There is only one daughter (|ABplapapaa)| -- for some reason it is 
copied into both the "Daughter A" and "Daughter B" column for Parent 
#404 (row 405). The values for one are rounded to two decimal places and 
the other is not. And the entry for |ABplapapaa in row 406 as a daughter 
without children is correct. |As for Parent #406 (row 407), you can 
ignore that entry, as the x,y,z position is inconsistent with the 
Daughter Cell entries (I'm not sure what this position refers to, since 
I cannot confirm this position with the dataset).


On 5/22/2016 12:24 PM, Mark Watts wrote:
>
> @balicea <https://github.com/balicea> in other places, I see that 
> there is only one daughter entry, either A or B. For some of these, 
> the 'Larger Cell' column shows 'X' for missing when there's only one 
> cell, and for others it shows 'A' when there's only an A daughter 
> cell. The row in my comment above is the only one where the same 
> daughter cell is in both A and B columns.
> Looking at Sulston et al's lineage tree it looks like:
>
> |406 ABplapapaa X 0 0 |
>
> should be
>
> |406 ABplapapap X 0 0 |
>
> except that, post-ebryonic blast cells are excluded from this data 
> set, so I think I'd just delete that line except that there's separate 
> positional data for 405 and 406. Is there any guidance on how to 
> resolve this? If not I'll try to highlight this data in some way in a 
> visualization.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/balicea/DevoWorm/issues/46#issuecomment-220844610>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
