### ISSUE TITLE
Resolve un-parented cell entries in differentiation tree spreadsheet

### ISSUE THREAD

**Issue by mwatts15** [balicea/DevoWorm#75]
In working with [this file](https://github.com/balicea/DevoWorm/blob/master/Differentiation%20Tree%20Dataset/differentiation-tree-all-variables.xlsx), I found a few cell entries, other than P0, that are without a parent. These should be resolved such that each mother-daughter link is represented without relying on implicit relationships or on external data sources.

ABprapp
MSpap
ABarpaaaa
ABarpaaap
ABarapapaa
ABplppapaa
ABpraaapp
ABprpapap

**Comment by mwatts15** [comment]
@balicea is there an earlier data source that the spreadsheet comes from? Some notes, maybe?

**Comment by balicea** [comment]
Mark,

Here are the data for the cells you listed (from a different master file). Order of numberic values should be x,y,z (as in the file you are working with):
ABprapp	459.6128062	273.7570302	15.13553026
MSpap	371.5199311	239.5351075	14.56264573
ABarpaaaa	230.9854344	259.7703629	15.88516009
ABarpaaap	258.3792251	261.6409993	15.8850886
ABarapapaa	289.5874098	258.0181299	14.22876545
ABplppapaa	359.7292533	226.0404918	14.95520446
ABpraaapp	310.2375163	278.1830907	15.08115306
ABprpapap	374.3496029	268.7215373	14.57011324

**Comment by mwatts15** [comment]
Thanks, Bradly. The problem I have is more that there's no indication if the cells without parents are the larger or smaller daughter cell or if they lack a sibling.

**Comment by balicea** [comment]
Here is the larger/smaller indication for this list of cells, with the rows representing cell in list, is cell in list larger or smaller?, sister cell ID:
ABprapp	Smaller	ABprapa
MSpap	Larger	MSpaa
ABarpaaaa	Larger	ABarpaaap
ABarpaaap	Smaller	ABarpaaaa
ABarapapaa	Smaller	ABarapapap
ABplppapaa	Smaller	ABplppapap
ABpraaapp	Larger	ABpraaapa
ABprpapap	Larger	ABprpappaa
