### ISSUE TITLE
Resolve self-loops in differentiation tree spreadsheet

### ISSUE THREAD

**Issue by mwatts15** [balicea/DevoWorm#76]
These cells have self-loops in the [spreadsheet](https://github.com/balicea/DevoWorm/blob/master/Differentiation%20Tree%20Dataset/differentiation-tree-all-variables.xlsx).

| Source      |
|-------------|
| ABarppapa   |
| ABarpppaa   |
| ABarppppa   |
| ABalapaaaa  |
| ABalapaapa  |
| ABalappppp  |
| ABalpaaaaa  |
| ABalpaaapa  |
| ABalpaapaa  |
| ABalpaapap  |
| ABalpaappa  |
| ABalpapaaa  |
| ABalpapaap  |
| ABalppappa  |
| ABalpppaaa  |
| ABalppppaa  |
| ABalpppppa  |
| ABaraaaaaa  |
| ABaraaaapa  |
| ABaraaapaa  |
| ABaraaappa  |
| ABaraapaaa  |
| ABaraapapp  |
| ABaraappaa  |
| ABaraapppp  |
| ABarapaaaa  |
| ABarapaapa  |
| ABarapaapp  |
| ABplaappa   |
| ABplappaa   |
| ABplpaapppp |
| ABplpapapa  |
| ABplpapapp  |
| ABplpapppa  |
| ABplppaapa  |
| ABplppappa  |
| ABplpppaaa  |
| ABplppppaa  |
| ABpraappa   |
| ABprapapppp |
| ABprpaaaap  |
| ABprpppaa   |

**Comment by balicea** [comment]
Mark,
Ignore daughter cells with same ID as mother cells (so-called self-loops). Again, ignore the daughters, not the mother cells. They are pretty far down the tree, and got appended as daughters for some reason.

**Comment by mwatts15** [comment]
Thanks Bradly. The problem I have is that these nodes are disconnected from P0 in the relative-size graph. I can reconnect based on the lineage name, but when there are two daughters and one has the same ID as the parent, does this mean it's actually an asymmetric division? In that case, what do the relative sizes mean?

**Comment by balicea** [comment]
We can also ignore the relative sizes for these cells as well. In some cases, there are asymmetric divisions -- these are cases where the lineage has finished differentiating, or where the daughter cells apoptose (programmed cell death). This is going to occur in later parts of the AB lineage, and much sooner in the C, D, and P lineages (although I think those are pre-excluded in this dataset). For our purposes (differentiation tree), we can simply exclude these cells and their information altogether, as they are not informative.

**Comment by balicea** [comment]
Yes, these cells represent asymmetric divisions, and do not have relative sizes. You may exclude them from the relative size graph. Later in the AB lineage (and much sooner in the C, D, and P lineages -- although these cases have been pre-excluded), you get asymmetric divisions either due to cells that finish differentiating or apoptosis (programmed cell death). For our purposes, these cells do not yield any information.
